// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/elct9620/gopherday2024/internal/app/rest"
	"github.com/elct9620/gopherday2024/internal/app/rest/v1"
	"github.com/go-chi/chi/v5"
)

// Injectors from wire.go:

func Initialize() (*chi.Mux, error) {
	v := v1.ProvideRotues()
	router := v1.New(v...)
	v2 := ProvideRouters(router)
	mux := rest.New(v2...)
	return mux, nil
}

// wire.go:

func ProvideRouters(
	v1Api *v1.Router,
) []rest.Router {
	return []rest.Router{rest.NewProbeRouter(), v1Api}
}
